---
# defaults file for Vessel

vessel_nsname: 'vessel'
vessel_tasks:
  linter:
    enabled: true
    scheduled: "{{ vessel_tasks_default_schedule }}"
  trivy:
    enabled: true
    scheduled: "{{ vessel_tasks_default_schedule }}"
vessel_tasks_modules:
  linter: 'vessel_collector.tasks.linter.VesselLinter'
  trivy: 'vessel_collector.tasks.trivy.Trivy'
vessel_tasks_default_schedule: 3600
